"""Deterministic utilities re-exported for the research pipeline."""

from .coverage import (
    render_markdown_report,
    summarize_evidence,
    summarize_gaps,
    summarize_search_candidates,
    summarize_source_visit,
    summarize_subqueries,
)
from .evidence import (
    build_report_sources,
    canonical_fingerprint,
    claims_are_approximate_duplicates,
    compute_minimum_coverage,
    compute_topic_coverages,
    curate_evidence,
    numeric_tokens,
    select_evidence_for_context,
    significant_tokens,
    total_evidence_tokens,
    update_working_dossier,
)
from .ranking import (
    build_search_query,
    choose_active_topic,
    classify_browser_payload,
    deduplicate_candidates,
    enrich_gaps_with_search_terms,
    prune_queue_by_domain,
    rank_topics_for_source,
    reformulate_queries,
    score_candidate,
    validate_candidate_for_topic,
)
from .text import (
    estimate_tokens,
    is_browser_noise_line,
    sanitize_source_title,
    select_relevant_chunks,
    short_excerpt,
    split_browser_payload,
    split_text,
)
from .url import TRACKING_QUERY_KEYS, canonicalize_url, extract_domain

__all__ = [
    "TRACKING_QUERY_KEYS",
    "build_report_sources",
    "build_search_query",
    "canonical_fingerprint",
    "choose_active_topic",
    "claims_are_approximate_duplicates",
    "classify_browser_payload",
    "compute_minimum_coverage",
    "compute_topic_coverages",
    "curate_evidence",
    "deduplicate_candidates",
    "enrich_gaps_with_search_terms",
    "estimate_tokens",
    "extract_domain",
    "is_browser_noise_line",
    "numeric_tokens",
    "prune_queue_by_domain",
    "rank_topics_for_source",
    "reformulate_queries",
    "render_markdown_report",
    "sanitize_source_title",
    "score_candidate",
    "select_evidence_for_context",
    "select_relevant_chunks",
    "short_excerpt",
    "split_browser_payload",
    "significant_tokens",
    "split_text",
    "summarize_evidence",
    "summarize_gaps",
    "summarize_search_candidates",
    "summarize_source_visit",
    "summarize_subqueries",
    "total_evidence_tokens",
    "update_working_dossier",
    "validate_candidate_for_topic",
    "canonicalize_url",
]
